# -*- coding: utf-8 -*-
"""Copia de Project III Etapa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_k3rfg60pKoMXsoeiEArBS4eaMEKfywk

# Instituto Tecnológico de Costa Rica | TEC
# Carrera de Ingeniería en Computación
# I Semestre de 2023
# Proyecto Programado (III Fase – Entrevistador asistido por IA)
# Dr. Abel Méndez Porras
#Estudiantes:
#Sharon Dayana Blanco Piedra
#Jennifer Miranda López
#Daniela Rodríguez Méndez
# amendez@itcr.ac.cr
# Porcentaje: 30%

# Entrevistador asistido por IA

El reconocimiento facial y la detección de emociones son tecnologías que se han vuelto cada vez más populares en los últimos años. Estas tecnologías utilizan algoritmos de inteligencia artificial para analizar imágenes y detectar patrones faciales que permiten identificar a las personas y sus emociones.
En cuanto a las oportunidades, el reconocimiento facial puede tener aplicaciones en la seguridad, el marketing y la atención al cliente. Por ejemplo, en la seguridad se pueden utilizar sistemas de reconocimiento facial para identificar a personas en lugares públicos o para controlar el acceso a edificios y sistemas de seguridad. En el marketing, se pueden utilizar para personalizar la publicidad en función de la edad, el género y otros datos demográficos. Y en la atención al cliente, se pueden utilizar para detectar la satisfacción del cliente en tiempo real y responder adecuadamente.

En esta tercera fase del proyecto del curso de Taller de Programación estaremos utilizando los resultados de consultas a modelos de Deep Learning para aplicar los conocimientos adquiridos en clase. Estaremos utilizando los requerimientos desarrollados para la segunda fase del proyecto. Sin embargo, se estarán utilizando widgets para hacer la recolección y mostrar la información para cada requerimiento desarrollado en la segunda fase. Además, se incluyen el manejo de árboles binarios para hacer busqueda de información.

## Objetivo
Desarrollar una aplicación de complejidad baja que permita poner en práctica los conocimientos adquiridos en los cursos de Introducción a la Programación y Taller de Programación.

## Objetivos Específicos
*  Identificar los requerimientos para resolver un problema específico desde la perspectiva de resolución de problemas, técnicas con listas, diccionarios, clases, objetos, archivos, árboles binarios y widgets.
*  Diseñar una aplicación para un problema específico desde la perspectiva de resolución de problemas, técnicas con listas, diccionarios, clases, objetos, archivos, árboles binarios y widgets.
*  Desarrollar una aplicación para un problema específico desde la perspectiva de resolución de problemas, técnicas con listas, diccionarios, clases, objetos, archivos, árboles binarios y widgets.

## Configuración previa

### Cargar Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Leer cámara
Tomado de https://colab.research.google.com/drive/1QnC7lV7oVFk5OZCm75fqbLAfD9qBy9bw?usp=sharing#scrollTo=ilLkpcKanPRb

### Importar dependencies
"""

# import dependencies
from IPython.display import display, Javascript, Image
from google.colab.output import eval_js
from base64 import b64decode, b64encode
import cv2
import numpy as np
import PIL
import io
import html
import time

"""### Convertir el objeto JavaScript un objeto OpenCV image"""

# function to convert the JavaScript object into an OpenCV image
def js_to_image(js_reply):
  """
  Params:
          js_reply: JavaScript object containing image from webcam
  Returns:
          img: OpenCV BGR image
  """
  # decode base64 image
  image_bytes = b64decode(js_reply.split(',')[1])
  # convert bytes to numpy array
  jpg_as_np = np.frombuffer(image_bytes, dtype=np.uint8)
  # decode numpy array into OpenCV BGR image
  img = cv2.imdecode(jpg_as_np, flags=1)

  return img

# function to convert OpenCV Rectangle bounding box image into base64 byte string to be overlayed on video stream
def bbox_to_bytes(bbox_array):
  """
  Params:
          bbox_array: Numpy array (pixels) containing rectangle to overlay on video stream.
  Returns:
        bytes: Base64 image byte string
  """
  # convert array into PIL image
  bbox_PIL = PIL.Image.fromarray(bbox_array, 'RGBA')
  iobuf = io.BytesIO()
  # format bbox into png for return
  bbox_PIL.save(iobuf, format='png')
  # format return string
  bbox_bytes = 'data:image/png;base64,{}'.format((str(b64encode(iobuf.getvalue()), 'utf-8')))

  return bbox_bytes

"""### Crear nuestro live video stream"""

# JavaScript to properly create our live video stream using our webcam as input
def video_stream():
  js = Javascript('''
    var video;
    var div = null;
    var stream;
    var captureCanvas;
    var imgElement;
    var labelElement;

    var pendingResolve = null;
    var shutdown = false;

    function removeDom() {
       stream.getVideoTracks()[0].stop();
       video.remove();
       div.remove();
       video = null;
       div = null;
       stream = null;
       imgElement = null;
       captureCanvas = null;
       labelElement = null;
    }

    function onAnimationFrame() {
      if (!shutdown) {
        window.requestAnimationFrame(onAnimationFrame);
      }
      if (pendingResolve) {
        var result = "";
        if (!shutdown) {
          captureCanvas.getContext('2d').drawImage(video, 0, 0, 640, 480);
          result = captureCanvas.toDataURL('image/jpeg', 0.8)
        }
        var lp = pendingResolve;
        pendingResolve = null;
        lp(result);
      }
    }

    async function createDom() {
      if (div !== null) {
        return stream;
      }

      div = document.createElement('div');
      div.style.border = '2px solid black';
      div.style.padding = '3px';
      div.style.width = '100%';
      div.style.maxWidth = '600px';
      document.body.appendChild(div);

      const modelOut = document.createElement('div');
      modelOut.innerHTML = "<span>Status:</span>";
      labelElement = document.createElement('span');
      labelElement.innerText = 'No data';
      labelElement.style.fontWeight = 'bold';
      modelOut.appendChild(labelElement);
      div.appendChild(modelOut);

      video = document.createElement('video');
      video.style.display = 'block';
      video.width = div.clientWidth - 6;
      video.setAttribute('playsinline', '');
      video.onclick = () => { shutdown = true; };
      stream = await navigator.mediaDevices.getUserMedia(
          {video: { facingMode: "environment"}});
      div.appendChild(video);

      imgElement = document.createElement('img');
      imgElement.style.position = 'absolute';
      imgElement.style.zIndex = 1;
      imgElement.onclick = () => { shutdown = true; };
      div.appendChild(imgElement);

      const instruction = document.createElement('div');
      instruction.innerHTML =
          '<span style="color: red; font-weight: bold;">' +
          'When finished, click here or on the video to stop this demo</span>';
      div.appendChild(instruction);
      instruction.onclick = () => { shutdown = true; };

      video.srcObject = stream;
      await video.play();

      captureCanvas = document.createElement('canvas');
      captureCanvas.width = 640; //video.videoWidth;
      captureCanvas.height = 480; //video.videoHeight;
      window.requestAnimationFrame(onAnimationFrame);

      return stream;
    }
    async function stream_frame(label, imgData) {
      if (shutdown) {
        removeDom();
        shutdown = false;
        return '';
      }

      var preCreate = Date.now();
      stream = await createDom();

      var preShow = Date.now();
      if (label != "") {
        labelElement.innerHTML = label;
      }

      if (imgData != "") {
        var videoRect = video.getClientRects()[0];
        imgElement.style.top = videoRect.top + "px";
        imgElement.style.left = videoRect.left + "px";
        imgElement.style.width = videoRect.width + "px";
        imgElement.style.height = videoRect.height + "px";
        imgElement.src = imgData;
      }

      var preCapture = Date.now();
      var result = await new Promise(function(resolve, reject) {
        pendingResolve = resolve;
      });
      shutdown = false;

      return {'create': preShow - preCreate,
              'show': preCapture - preShow,
              'capture': Date.now() - preCapture,
              'img': result};
    }
    ''')

  display(js)

def video_frame(label, bbox):
  data = eval_js('stream_frame("{}", "{}")'.format(label, bbox))
  return data

"""### Iniciar streaming video"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image, ImageDraw, ImageFont

import cv2
import numpy as np
import tensorflow as tf
from keras.models import model_from_json

"""### Cargar modelos de Deep Learning entrenados

*   Para detectar los rostros se utiliza el modelo de Face Haar Cascade.
*   Para detectar las emociones se utiliza el modelo de VGG.
*   También se utiliza un algoritmo adicional para pasar la información del algortimo de VGG a un formato JSON.

Estos modelos y algoritmos están disponibles en el siguiente enlace [Descargar modelos y algoritmos](https://drive.google.com/drive/folders/1KctA_s25bqqMOUlQuy0lwTm0HkBGVycF?usp=sharing). Usted los debe colocar en su Google Drive y modificar la ruta de acceso.
"""

#Cargar modelos de Deep Learning entrenados
face_haar_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/images/haarcascade_frontalface_alt.xml')
model = model_from_json(open("/content/drive/MyDrive/images/model.json", "r").read())
model.load_weights('/content/drive/MyDrive/images/model.h5')

"""Crear interfaz
https://www.youtube.com/watch?v=oIVmV41uyK8

#Perfiles del Entrevistador Personal

El entrevistador personal es una herramienta para recolectar información de personas que están aplicando a un puesto. En la aplicación existen tres perfiles el entrevistador, el entrevistado y el evaluador. La información de estos perfiles debe ser almacenada en clases y usando herencia. Debe existir una clase "padre" que tiene propiedades y métodos que comparten todos los perfiles. Para cada perfil debe existir una clase subordinada que hereda las propiedades de la clase "padre", además, tiene sus propias propiedades y métodos.

## Recolectar información del entrevistador

El entrevistador es la persona encargada de realizar las entrevistas.

Información requerida del entrevistador (Toda la información requerida debe ser almacenada en la clase Entrevistador. Cada vez que se registra un entrevistador se debe crear una instancia de la clase Entrevistador para guardar toda la información del entrevistador).
*   Identificación  
*   Nombre
*   Fecha de nacimiento
*   Nacionalidad
*   Números de teléfono y celular (un diccionario)
*   Emails (una lista con uno o varios emails)
*   Dirección

Usted debe incluir al menos tres propiedades únicas al entrevistador.
Cada vez que se crea una instancia de Entrevistador, la instancia debe ser almacenada en un archivo binario llamado Archivo_Entrevistador.

## Recolectar información del evaluador

El evaluador en la persona encargada de revisar la información obtenida de cada entrevista.

Información requerida del evaluador (Toda la información requerida debe ser almacenada en la clase Evaluador. Cada vez que se registra un evaluador se debe crear una instancia de la clase Evaluador para guardar toda la información del evaluador).
*   Identificación  
*   Nombre
*   Fecha de nacimiento
*   Nacionalidad
*   Números de teléfono y celular (un diccionario)
*   Emails (una lista con uno o varios emails)
*   Dirección

Usted debe incluir al menos tres propiedades únicas al evaluador.
Cada vez que se crea una instancia de Evaluador, la instancia debe ser almacenada en un archivo binario llamado Archivo_Evaluador.

## Recolectar información del entrevistado

El entrevistado es la persona que está interesada en el puesto de trabajo.

Información requerida al entrevistar una persona (Toda la información requerida debe ser almacenada en la clase Entrevistado. Cada vez que se registra un entrevistado se debe crear una instancia de la clase Entrevistado para guardar toda la información del entrevistado).
*   Identificación  
*   Nombre
*   Fecha de nacimiento
*   Nacionalidad
*   Números de teléfono y celular (un diccionario)
*   Emails (una lista con uno o varios emails)
*   Dirección
*   Estado civil
*   Cantidad de hijos indicando el género, la fecha de nacimiento(un diccionario)
*   Entrevistas (cada persona puede ser entrevistada cero o más veces). Las entrevistas se realizan en tiempo real utilizando una camára integrada a la computadora o externa (el profesor facilita el código para activar la camára, capturar el video y capturar los frames cada cierto tiempo). Se debe crear una lista con sublistas donde cada sublista tiene las imagenes capturas y las emociones reportadas durante la entrevista. Además, debe guardar coordenadas donde se encuentra el rostro en la imagen. Para cada entrevista, el entrevistado debe contar historias cortas sobre los siguientes 4 tópicos:


  >*   Una experiencia de sorpresa o asombro que ha tenido que vivir.
  >*   Una experiencia de tristeza que ha tenido que vivir.
  >*   Una experiencia de enojo o frustración que ha tenido que vivir.
  >*   Una experiencia de felicidad que ha tenido que vivir.

Un aspecto importante es que cada vez que se va a realizar una entrevista se debe indicar quién es el entrevistador.

Usted debe incluir al menos tres propiedades únicas al perfil de entrevistado. Cada vez que se crea una instancia de Entrevistado, la instancia debe ser almacenada en un archivo binario llamado Archivo_Entrevistado.
"""

def show_image(image_path):
  """ This function shows an image.
    Arguments:
        image_path {str} -- Image path.
  """
  img = cv2.imread(image_path)
  img_cvt=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  plt.imshow(img_cvt)
  plt.show()
#Code taken from ordenamientos de "Reconocimiento de Personas" in week 8 of Introducción a la Programación.

class Person():
  def __init__(self, identification, name, birth_date, age, nationality, telephone_numbers, gender, emails, address):
    """Forms a instance of a person"""
    self.name = name
    self.identification = identification
    self.birth_date = birth_date
    self.age = age
    self.nationality = nationality
    self.telephone_numbers = telephone_numbers
    self.gender = gender
    self.emails = emails
    self.address = address

class Interviewer(Person):
  """Forms a instance of an interviewer and enherits the class named Person"""
  def __init__(self, identification, name, birth_date, age, nationality, telephone_numbers, gender, emails, address, code_number, certificate, experience):
   super().__init__(identification, name, birth_date, age, nationality, telephone_numbers, gender, emails, address)
   self.code_number = code_number
   self.certificate = certificate
   self.experience = experience
  def __str__(self):
    """This method is for printing the instance information"""
    return f"name: {self.name}, identification: {self.identification}, birth_date: {self.birth_date}, age: {self.age}, nationality: {self.nationality}, telephone_numbers: {self.telephone_numbers}, gender: {self.gender}, emails: {self.emails}, address: {self.address}, code_number: {self.code_number}, certificate: {self.certificate}, experience: {self.experience}"



class Evaluator(Person):
  def __init__(self, identification, name, birth_date, age, nationality, telephone_numbers, gender, emails, address, specialty, technical_programs, languages):
   """Forms a instance of an evaluator and enherits the class named Person"""
   super().__init__(identification, name, birth_date, age, nationality, telephone_numbers, gender, emails, address)
   self.specialty = specialty
   self.technical_programs = technical_programs
   self.languages = languages
  def __str__(self):
    """This method is for printing the instance information"""
    return f"name: {self.name}, identification: {self.identification}, birth_date: {self.birth_date}, age: {self.age}, nationality: {self.nationality}, telephone_numbers: {self.telephone_numbers}, gender: {self.gender}, emails: {self.emails}, address: {self.address}, specialty: {self.specialty}, technical_programs: {self.technical_programs}, languages: {self.languages}"





class Interviewee(Person):
  def __init__(self, identification, name, birth_date, age, nationality, telefone_numbers, gender, emails, address, marital_status, children, job, salary, academic_grade, happiness,state, images):
   """Forms a instance of an interviewee and enherits the class named Person"""
   super().__init__(identification, name, birth_date, age, nationality, telefone_numbers, gender, emails, address)
   self.marital_status = marital_status
   self.children = children
   self.job = job
   self.salary = salary
   self.academic_grade = academic_grade
   self.state = state
   self.images = images
   self.happiness = happiness
  def __str__(self):
    """This method is for printing the instance information"""
    return f"name: {self.name}, identification: {self.identification}, birth_date: {self.birth_date}, age: {self.age}, nationality: {self.nationality}, telephone_numbers: {self.telephone_numbers}, gender: {self.gender}, emails: {self.emails}, address: {self.address}, marithal_status: {self.marital_status}, children: {self.children}, job: {self.job}, salary: {self.salary}, academic_grade: {self.academic_grade}, happiness: {self.happiness} state: {self.state}, images: {self.images}"

"""### Recolectar información emociones
Este código se encarga de ejecutar la captura de video de la cámara, detectar los rostros en las imágenes y reconocer las emociones presentes en los rostros. Cuando se hace la entrevista es en este código donde usted de obtener la información para crear las listas con la información solicitada.
"""

import pickle
j = 5
with open("/content/drive/MyDrive/Archive_III_project/Archivo_j", "wb") as entre:
    pickle.dump(j, entre)

from tensorflow.python.ops.math_ops import sign
# start streaming video from webcam
video_stream()
# label for video
label_html = 'Capturing...'
# initialze bounding box to empty
bbox = ''
count = 0
listn = []
while True:
  js_reply = video_frame(label_html, bbox)
  if not js_reply:
    break

  # convert JS response to OpenCV Image
  img = js_to_image(js_reply["img"])
  img_copy = img

  # create transparent overlay for bounding box
  bbox_array = np.zeros([480,640,4], dtype=np.uint8)
  with open("/content/drive/MyDrive/Archive_III_project/Archivo_j", "rb") as entre:
   j = pickle.load(entre)

  if count == j: #El tiempo para capturar el frame y procesarlo
    #Este sería el path de la imagen guardada
    image_path ='/content/drive/MyDrive/Frames_III_Project/' + 'nombre' + str(j) +  '.jpg'
    #se guarda el fotograma con el "nombre" más el número del contador i
    cv2.imwrite(image_path , img)
    listn.append(image_path)
    #Detectar los rostros usando Face Haar Cascade
    gray_image = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    #En faces_deteted se encuentran los rotros detectados
    faces_detected = face_haar_cascade.detectMultiScale(gray_image,1.32,5)
    #Imprimir ubicación de los rostros en la imagen
    print("Ubicación del rostro:", faces_detected)
    im2Display = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    imTemp = im2Display.copy()
    listn.append([faces_detected])
    #Hacer un rectángulo en cada rostro detectado en la imagen
    for (x,y,w,h) in faces_detected:
        cv2.rectangle(img,(x,y), (x+w,y+h), (255,0,0), thickness=7)

        roi_gray=gray_image[y:y+w,x:x+h]
        roi_gray=cv2.resize(roi_gray,(48,48))

        #Processes the image and adjust it to pass it to the model
        image_pixels = tf.keras.preprocessing.image.img_to_array(roi_gray)

        image_pixels = np.expand_dims(image_pixels, axis = 0)
        image_pixels /= 255

        #Obtener las emociones para cada rostro detectado en la imagen
        #Get the prediction of the model
        predictions = model.predict(image_pixels)
        #Mostrar todas las emociones detectadas
        print("Predicciones: ", predictions)
        #Mostrar la emoción más significativa (con el valor más alto)
        max_index = np.argmax(predictions[0])
        print(max_index, predictions[0])
        #El orden en que vienen las emociones
        emotion_detection = ('angry', 'disgust', 'fear', 'happyness', 'sadness', 'surprise', 'neutral')

        emotion_prediction = emotion_detection[max_index]
        #Crear un diccionario para almacenar la emoción y el valor para la emoción
        frame_dic = dict(
            angry = predictions[0][0],
            disgust = predictions[0][1],
            fear = predictions[0][2],
            happiness = predictions[0][3],
            sadness = predictions[0][4],
            surprise = predictions[0][5],
            neutral = predictions[0][6])
        print("Predicciones: ", frame_dic)
        listn.append(frame_dic)
        print( emotion_prediction )

        #Mostrar en la imagen un texto de la emoción más significativa
        ubicacion = (x,y)
        font = cv2.FONT_HERSHEY_TRIPLEX
        tamañoLetra = 2
        colorLetra = (221,82,196)
        grosorLetra = 7
        #Escribir texto con la emoción más significativa
        cv2.putText(imTemp, emotion_prediction, ubicacion, font, tamañoLetra, colorLetra, grosorLetra)
        pt1 = (x, y)
        pt2 = (x+w, y+h)
        color = (23,200,54)
        thickness = 10
        cv2.rectangle(imTemp, pt1, pt2, color, thickness)

    #Mostrar la imagen con los cuadros en los rostros y el texto de la emoción más significativa
    plt.imshow(imTemp)
    plt.show()
    j +=5
    with open("/content/drive/MyDrive/Archive_III_project/Archivo_j", "wb") as entre:
      pickle.dump(j, entre)
  count +=1

"""# Objetos Gráficos



1.   Debe implementar Widgets para la información a recolectar y mostrar para cada uno de los requerimientos del proyecto. A continuación, se listan los principales tipos de widgets que debe utilizar en el proyecto.
  

    *   Numeric widgets
    *   Boolean widgets
    *   Selection widgets
    *   String widgets
    *   Image
    *   Tag widgets
    *   Date picker
    *   Time picker
    *   Color picker
    *   File Upload
    *   Container/Layout widgets


"""

empty_list = []

with open("/content/drive/MyDrive/Archive_III_project/Archivo_Evaluador", "wb") as entre:
      pickle.dump(empty_list, entre)

with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistador", "wb") as entre:
      pickle.dump(empty_list, entre)

with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistado", "wb") as entre:
      pickle.dump(empty_list, entre)

#Libraries to use ipy widgets
from ipywidgets.widgets.domwidget import InstanceDict
import pickle
import ipywidgets as widgets
from ipywidgets import interact, interactive, fixed, interact_manual
from ipywidgets import HBox, Label
from ipywidgets import Button, HBox, VBox


#----------------------------------------function to save the evaluator instances-----------------------------------------
def archive_evaluator(Instance):
 """The function saves the evaluator instance in a pickle archive.
    Arguments:
        Instance {str} -- Instance.
 """
 with open("/content/drive/MyDrive/Archive_III_project/Archivo_Evaluador", "rb") as entre:
    Archive_evaluator = pickle.load(entre)
 for x in Archive_evaluator:
    if x.identification == Instance.identification:
       Archive_evaluator.remove(x)
 Archive_evaluator.append(Instance)
 with open("//content/drive/MyDrive/Archive_III_project/Archivo_Evaluador", "wb") as entre:
      pickle.dump(Archive_evaluator, entre)
 print("The information has been saved")


#----------------------------------------function to save the interviewer instances-----------------------------------------
def archive_interviewer(Instance):
 """The function saves the interviewer instance in a pickle archive.
    Arguments:
        Instance {str} -- Instance.
 """
 with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistador", "rb") as entre:
    Archive_interviewer = pickle.load(entre)
 for x in Archive_interviewer:
    if x.identification == Instance.identification:
       Archive_interviewer.remove(x)
 Archive_interviewer.append(Instance)
 with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistador", "wb") as entre:
      pickle.dump(Archive_interviewer, entre)
 print("The information has been saved")


#----------------------------------------function to save the interviewer instances-----------------------------------------
def archive_interviewee(Instance):
 """The function saves the interviewee instance in a pickle archive.
    Arguments:
        Instance {str} -- Instance.
 """
 with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistado", "rb") as entre:
    Archive_interviewee = pickle.load(entre)
 for x in Archive_interviewee:
    if x.identification == Instance.identification:
       Archive_interviewee.remove(x)
 Archive_interviewee.append(Instance)
 with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistado", "wb") as entre:
      pickle.dump(Archive_interviewee, entre)
 print("The information has been saved")



def evaluator():
 """This function creates an evaluator instance using widgets.
 """
 #Code to ask all the individual's information
 name = widgets.Text(
    value='Place your name',
    placeholder='Type something',
    description='Name:',
    disabled=False
 )
 ID = widgets.BoundedIntText(
    value=7,
    min=0,
    max=1000000000,
    step=1,
    description='ID:',
    disabled=False
)
 birth_date = widgets.DatePicker(
    description='Birth date: ',
    disabled=False
 )
 age = widgets.BoundedIntText(
    value=0,
    min=0,
    max= 200,
    step=1,
    description='Age: ',
    disabled=False
 )
 nationality = widgets.Text(
    value='Place your nationality',
    placeholder='Type something',
    description='Nationality:',
    disabled=False
 )
 telephone = widgets.BoundedIntText(
    value=0,
    min=0,
    max=1000000000,
    step=1,
    description='Telephone: ',
    disabled=False
 )
 gender =  size = widgets.Dropdown(
    options=['female', 'male'],
    value='male',
    description='Gender: ',
    disabled=False,
 )
 email =  widgets.Text(
    value='Place your email',
    placeholder='Type something',
    description='Email:',
    disabled=False
 )
 address = widgets.Text(
    value='Place your address',
    placeholder='Type something',
    description='Address:',
    disabled=False
 )
 specialty = widgets.Text(
    value='Place your specialty',
    placeholder='Type something',
    description='Specialty:',
    disabled=False
 )
 technical_programs = widgets.Text(
    value='Place your technical programs',
    placeholder='Type something',
    description='Programs:',
    disabled=False
 )
 languages = widgets.IntSlider(
    value=7,
    min=0,
    max=10,
    step=1,
    description='Languages:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
 boton = widgets.Button(
    description = "Save information"
 )

 #Box to save the buttons.
 container = widgets.VBox([name, ID , birth_date, age, nationality, telephone, gender, email, address, specialty, technical_programs, languages, boton])
 def savedata(b):
   """This function creates an instance of a person and directs it to another function"""
   Person = Evaluator(ID.value, name.value, birth_date.value, age.value, nationality.value, telephone.value, gender.value, email.value, address.value, specialty.value, technical_programs.value, languages.value)
   archive_evaluator(Person)

 #Code to go to the function savedata if the button is clicked.
 boton.on_click(savedata)

 #Code to display the container.
 display(container)




def interviewer():
 """This function creates an interviewer instance using widgets.
 """
 #Code to ask all the individual's information
 name = widgets.Text(
    value='Place your name',
    placeholder='Type something',
    description='Name:',
    disabled=False
 )
 ID = widgets.BoundedIntText(
    value=7,
    min=0,
    max=1000000000,
    step=1,
    description='ID:',
    disabled=False
 )
 birth_date = widgets.DatePicker(
    description='Birth date: ',
    disabled=False
 )
 age = widgets.BoundedIntText(
    value=0,
    min=0,
    max=200,
    step=1,
    description='Age: ',
    disabled=False
 )
 nationality = widgets.Text(
    value='Place your nationality',
    placeholder='Type something',
    description='Nationality:',
    disabled=False
 )
 telephone = widgets.BoundedIntText(
    value=0,
    min=0,
    max=1000000000,
    step=1,
    description='Telephone: ',
    disabled=False
 )
 gender = widgets.Dropdown(
    options=['female', 'male'],
    value='male',
    description='Gender: ',
    disabled=False,
 )
 email =  widgets.Text(
    value='Place your email',
    placeholder='Type something',
    description='Email:',
    disabled=False
 )
 address = widgets.Text(
    value='Place your address',
    placeholder='Type something',
    description='Address:',
    disabled=False
 )
 code_number= widgets.BoundedIntText(
    value=0,
    min=0,
    max=99999,
    step=1,
    description='Code: ',
    disabled=False
 )
 certificate = widgets.BoundedIntText(
    value=0,
    min=0,
    max=99999,
    step=1,
    description='Certificate: ',
    disabled=False
 )
 experience = widgets.IntSlider(
    value=7,
    min=0,
    max=100,
    step=1,
    style = {'description_width': 'initial'},
    description='Experience years:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
 )
 boton = widgets.Button(
    description = "Save information"
 )

 #Box to save the buttons.
 container = widgets.VBox([name, ID , birth_date, age, nationality, telephone, gender, email, address, code_number, certificate, experience, boton])
 def savedata(b):
   """This function creates an instance of a person and directs it to another function"""
   Person = Interviewer(ID.value, name.value, birth_date.value, age.value, nationality.value, telephone.value, gender.value, email.value, address.value, code_number.value, certificate.value, experience.value)
   archive_interviewer(Person)

 #Comand to go to the function savedata if the button is clicked.
 boton.on_click(savedata)

 #Code to display the container.
 display(container)


def interviewee():
 """This function creates an interviewer instance using widgets.
 """
 #Code to ask all the individual's information
 name = widgets.Text(
    value='Place your name',
    placeholder='Type something',
    description='Name:',
    disabled=False
 )
 ID = widgets.BoundedIntText(
    value=7,
    min=0,
    max=1000000000,
    step=1,
    description='ID:',
    disabled=False
 )
 birth_date = widgets.DatePicker(
    description='Birth date: ',
    disabled=False
 )
 age = widgets.BoundedIntText(
    value=0,
    min=0,
    max=200,
    step=1,
    description='Age: ',
    disabled=False
 )
 nationality = widgets.Text(
    value='Place your nationality',
    placeholder='Type something',
    description='Nationality:',
    disabled=False
 )
 telephone = widgets.BoundedIntText(
    value=0,
    min=0,
    max=1000000000,
    step=1,
    description='Telephone: ',
    disabled=False
 )
 gender =  size = widgets.Dropdown(
    options=['female', 'male'],
    value='male',
    description='Gender: ',
    disabled=False,
 )
 email =  widgets.Text(
    value='Place your email',
    placeholder='Type something',
    description='Email:',
    disabled=False
 )
 address = widgets.Text(
    value='Place your address',
    placeholder='Type something',
    description='Address:',
    disabled=False
 )
 marital_status = widgets.ToggleButtons(
    options=['Single', 'Married', 'Divorced', 'Widowed', 'Separated'],
    style = {'description_width': 'initial'},
    description='Marital status:',
    disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltips=['Description of slow', 'Description of regular', 'Description of fast'],
 #     icons=['check'] * 3
 )


 #----------------------Functions to create the dictionary children-------------------------------------------------------
 def create_dictionary(amount_children):
                """The function creates and saves  a dictionary with the children's information.
                Arguments:
                amount_children {int} -- Amount of children.
                """
                children.clear()
                info = []
                def save_info(change):
                   """The function saves in a list the gender and birth date of the children.
                   Arguments:
                   change {int} -- Amount of children.
                   """
                   info = []
                   #Code to update the children information in the dictionary
                   for i in range(amount_children):
                      gender_value = gender_list[i].value
                      birth_date_value = birth_date_list[i].value

                      info.append([gender_value, str(birth_date_value)])

                   children["number"] = amount_children
                   children["info"] = info


                gender_list = []
                birth_date_list = []

                #Code to recollect children's information
                for i in range(amount_children):
                  gender = widgets.Label(value=f"Child {i+1} gender:")
                  gender_ = widgets.Dropdown(
                  options=['female', 'male'],
                  value='male',
                  description='Gender:',
                  disabled=False
                  )

                  birth_date = widgets.Label(value=f"Child {i+1} birth date:")
                  birth_date_ = widgets.DatePicker(
                  description='Birth date:',
                  disabled=False
                  )

                  gender_list.append(gender_)
                  birth_date_list.append(birth_date_)

                  display(gender, gender_, birth_date, birth_date_)

                for w in gender_list + birth_date_list:
                    w.observe(save_info, names='value')

                save_info(None)
                display(job, salary, academic_grade, state, boton)
 num_label = widgets.Label(value="Amount of children:")
 num_amount = widgets.BoundedIntText(
    value=0,
    min=0,
    max=10,
    step=1,
    disabled=False
 )
 number_button = widgets.Button(description="Save")
 children = {}

 def number_button_clicked(b):
    """This function directs the operation to another function and stablishes
    the variable amount_children based on the input
    """
    amount_children = num_amount.value
    create_dictionary(amount_children)

#-------------------------------End of the functions----------------------------------------------

 job = widgets.Text(
    value='Place your job',
    placeholder='Type something',
    description='Job:',
    disabled=False
 )

 salary = widgets.BoundedIntText(
    value=0,
    min=0,
    max=10000000,
    step=1,
    description='Salary: ',
    disabled=False
 )

 academic_grade = widgets.ToggleButtons(
    options =['School completed', 'School incompleted', 'Highchool completed', 'Highschool incompleted', 'University completed', 'University incompleted'],
    style = {'description_width': 'initial',},
    description='Academic grade:',
    disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltips=['Description of slow', 'Description of regular', 'Description of fast'],
 #     icons=['check'] * 3
 )


 state = widgets.Dropdown(
    options=['Interviewed'],
    value='Interviewed',
    description='State: ',
    disabled=False,
 )
 # Code to classify the information of the images in sub lists of 3 values inside a list.
 images = []
 c = 0
 p = 3
 pp = []
 a = len(listn)
 while c < a:
  for x in listn:
    pp.append(x)
    p = p - 1
    a = a - 1
    if p == 0:
      images.append(pp)
      pp = []
      p = 3

 #Code to recollect the highest happiness
 m = 0
 for x in images:
   if x[2]["happiness"] > m:
     m = x[2]["happiness"]
 happiness = m


 boton = widgets.Button(
    description = "Save information"
 )
# Box to save all buttons.
 container = widgets.VBox([name, ID , birth_date, age, nationality, telephone, gender, email, address, marital_status, num_label, num_amount, number_button])
 def savedata(b):
   """This function creates an instance of a person and directs it to another function"""
   Person = Interviewee(ID.value, name.value, str(birth_date.value), age.value, nationality.value, telephone.value, gender.value, email.value, address.value, marital_status.value, children, job.value, salary.value, academic_grade.value, happiness, state.value, images)
   archive_interviewee(Person)
 number_button.on_click(number_button_clicked)

 #Code to display the container.
 display(container)

 #Comand to go to the function savedata if the button is clicked.
 boton.on_click(savedata)

from ipython_genutils.py3compat import buffer_to_bytes
from sys import builtin_module_names
#Menu to create new instances
def but_(_):
    """This function calls another function depending on a value given.
    """
    v = l.value
    if v == 1:
      evaluator()
    elif v == 2:
      interviewer()
    else:
      interviewee()


# Asks for the number of profile.
print("What is your profile?: ")
print("\nEvaluator 1","\nInterviewer 2","\nInterviewee 3","\nFinish 0" )
print("Place your profile number")
l = widgets.BoundedIntText(
    value=7,
    min=0,
    max=3,
    step=1,
    description='ID:',
    disabled=False
    )


#Creates a button to save the value.
but = widgets.Button(
description = "Submit"
)


#Displays both buttons.
display(l)
display(but)

#Comand to go to the function but_ if the buttton is pressed.
but.on_click(but_)

#Library pickle to save archives.
import pickle
#Code to read all the information from the archives and save them in a variable.
with open("/content/drive/MyDrive/Archive_III_project/Archivo_Evaluador", "rb") as entre:
    Archive_evaluator = pickle.load(entre)
for x in Archive_evaluator:
  print(x)
print("---------")
with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistador", "rb") as entre:
  Archive_interviewer = pickle.load(entre)
for x in Archive_interviewer:
    print(x)
with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistado", "rb") as entre:
  Archive_interviewee = pickle.load(entre)
print("---------")
for x in Archive_interviewee:
  print(x)

"""# Árboles binarios


1.   Implementar un árbol binario para almacenar de forma ordenada las personas por edad (Cada nodo del árbol debe contener una instancia de la clase Entrevistado).
2.   Implementar un árbol binario para almacenar de forma ordenada las personas por por la emoción de felicidad (Cada nodo del árbol debe contener una instancia de la clase Entrevistado).

3. Implementar una función que muestre la información del árbol implementado en el punto 1 en orden (Debe mostrar la información usando widgets).


4. Implementar una función que muestre la información del árbol implementado en el punto 2 en preorden (Debe mostrar la información usando widgets).


5. Implementar una función que buscar una persona por la identificación en el árbol implementado en el punto 1.

6. Implementar una función que buscar una persona por el nombre en el árbol implementado en el punto 2.

7. Implementar una función que buscar muestre todas las personas que tienen el grado de felicidad más alto en el árbol implementado en el punto 1.

#Inquiry 1
 Implement a binary tree to save each interviewed person based on their age.
#Inquiry 3
 Implement a function that shows the information of the first binary tree in order using widgets.
"""

class Node():
    """Class Node"""

    def __init__(self, person):
        """Stablishes the attributes of Node"""
        self.left  = None
        self.right = None
        self.person = person

class Tree():
    """Class Tree"""

    def __init__(self):
        """Stablishes an empty root of a binary tree"""
        self.root = None

    def insert(self, person):
        """Inserts the value of the binary root"""
        if self.root == None:
            self.root = Node(person)
        else:
            self._insert(person, self.root)

    def _insert(self, person, node):
        """Inserts the new instances based on their age"""
        if person.age < node.person.age:
            if node.left != None:
                self._insert(person, node.left)
            else:
                node.left = Node(person)
        else:
            if node.right != None:
                self._insert(person, node.right)
            else:
                node.right = Node(person)

    def in_order(self, node):
        """Shows the information of the instances in order"""
        if node == None:
            return None
        else:
            self.in_order(node.left)
            show_individual_info(node.person)
            self.in_order(node.right)


    def look_for_ID(self, node, person):
        """Looks for a person based on their ID number"""
        if node == None:
            return None
        elif node.person.identification == person.identification:
            show_individual_info(node.person)
        else:
            self.look_for_ID(node.left, person)
            self.look_for_ID(node.right, person)


    def prin_high(self, node, m, lis = []):
      """This function prints the instances with the highest happiness"""
      if node == None:
            return None
      elif node.person.happiness == m.happiness and node.person not in lis:
            lis.append(node.person)
            #show_individual_info(node.person)
      self.prin_high(node.left, m)
      self.prin_high(node.right, m)
      return lis


    def highest_happiness(self, node):
      """Looks for the person with the highest happiness"""
      if node == None:
        return None
      m = node.person
      t = self.highest_happiness(node.right)
      if t != None and m.happiness < t.happiness:
        m = t
      p = self.highest_happiness(node.left)
      if p != None and m.happiness < p.happiness:
          m = p
      return m


#Code to insert the instances based on their age.
tree = Tree()
for x in Archive_interviewee:
  tree.insert(x)
print()

#Code to show the instances in order.
tree.in_order(tree.root)

"""#Inquiry 2
Implement a binary tree to save all interivewed people's information based on their emotion happiness.
#Inquiry 4
Inplement a function that shows the information of the second binary tree in pre order using widgets.
"""

class Node():
    """Class Node"""

    def __init__(self, person):
        """This method stablised the attributes of the nodes"""
        self.left  = None
        self.right = None
        self.person = person

class Tree2():
    """Class Tree"""

    def __init__(self):
        """Stablishes an empty root of a binary tree"""
        self.root = None

    def insert(self, person):
        """Inserts the value of the binary root"""
        if self.root == None:
            self.root = Node(person)
        else:
            self._insert(person, self.root)

    def _insert(self, person, node):
        """Inserts the new instances based on their happiness"""
        if person.happiness < node.person.happiness:
            if node.left != None:
                self._insert(person, node.left)
            else:
                node.left = Node(person)
        else:
            if node.right != None:
                self._insert(person, node.right)
            else:
                node.right = Node(person)


    def in_pre_order(self, node):
        """Shows the information of the instances in preorder"""
        if node == None:
            return None
        else:
            show_individual_info(node.person)
            self.in_pre_order(node.left)
            self.in_pre_order(node.right)


    def in_order(self, node):
        """Shows the information of the instances in order"""
        if node == None:
            return None
        else:
            self.in_order(node.left)
            show_individual_info(node.person)
            self.in_order(node.right)

    def look_for_name(self, node, person):
        """Looks for a person based on their name"""
        if node == None:
            return None
        elif node.person.name == person.name:
            show_individual_info(node.person)
        else:
            self.look_for_name(node.left, person)
            self.look_for_name(node.right, person)

#Code to insert the instances based on their age.
tree2 = Tree2()
for x in Archive_interviewee:
  tree2.insert(x)
#Code to show all the instances in preorder.
tree2.in_pre_order(tree2.root)

"""#Inquiry 5
Implement a function that looks for a person based on their identification in the first binary tree.


"""

def button_pressed(_):
    """This function looks for the ID of a person in a binary tree.
    """
    for x in Archive_interviewee:
        if x.identification == m.value:
          person = x
          tree.look_for_ID(tree.root, person)


# Asks for the ID of the person.
print("Place the ID number")
m = widgets.BoundedIntText(
    value=7,
    min=0,
    max=1000000000,
    step=1,
    description='ID:',
    disabled=False
    )


#Creates a button to search the information.
boton = widgets.Button(
description = "Submit"
)


#Displays both buttons.
display(m)
display(boton)

#Comand to go to the function button if the buttonn is pressed.
boton.on_click(button_pressed)

"""#Inquiry 6
Implement a function that looks for a person based on their names in the second binary tree.
"""

def button_(_):
    """This function looks for the ID of a person in a binary tree.
    """
    for x in Archive_interviewee:
        if x.name == w.value:
          person = x
          tree2.look_for_name(tree2.root, person)


# Asks for the name of the person.
print("Place the name")
w = widgets.Text(
    value="Write a name",
    description='Name:',
    disabled=False
    )

#Creates a button to search the information.
buttonn = widgets.Button(
description = "Submit"
)

#Displays both buttons.
display(w)
display(buttonn)
#Comand to go to the function button if the buttonn is pressed.
buttonn.on_click(button_)

"""#Inquiry 7
Implement a function that looks for the person or people who has the highest happiness in the first binary tree.
"""

#Code to show the person with the highest happiness
for x in Archive_interviewee:
  tree.insert(x)
  print(x.happiness)
vari = tree.prin_high(tree.root, tree.highest_happiness(tree.root))
for x in vari:
  show_individual_info(x)
#show_individual_info(tree.highest_happiness(tree.root))

"""# Consultas


1.   Mostrar la información de todas las personas entrevistas (la información debe ser mostrada siendo saca del archivo correspondiente, debe mostrar la información en formato legible, no en estructuras y objetos). Además, debe mostrar toda la información recolectada de la persona, se debe mostrar todas las imágenes que se recolectaron durante las entrevistas, las emociones reconocidas para cada imagen y las coordenadas donde se encuentra los rostros.

2.   Mostrar la información de todas las personas entrevistas ordenada ascendentemente por edad. El método de ordenamiento a utilizar es el método por inserción (la información debe ser mostrada siendo saca de los archivos, no se debe hacer simplemente la impresión en pantalla de la información obtenida de los archivos). Además, de mostrar toda la información recolectada de la persona, se debe mostrar todas las imágenes que se recolectaron durante las entrevistas, las emociones reconocidas para cada imagen y las coordenadas donde se encuentra los rostros.

3.   Mostrar la información de todas las personas entrevistas ordenada descendente mente por la cantidad de hijos. El método de ordenamiento a utilizar es el método por de la bubuja (la información debe ser mostrada siendo saca de los archivos, no se debe hacer simplemente la impresión en pantalla de la información obtenida de los archivos). Además, de mostrar toda la información recolectada de la persona, se debe mostrar todas las imágenes que se recolectaron durante las entrevistas, las emociones reconocidas para cada imagen y las coordenadas donde se encuentra los rostros.

4. Mostrar la información de todas las personas entrevistas ordenada descendentemente por la cantidad de hijos. El método de ordenamiento a utilizar es el método por de la quicksort (la información debe ser mostrada siendo sacada de los archivos, no se debe hacer simplemente la impresión en pantalla de la información obtenida de los archivos). Además, de mostrar toda la información recolectada de la persona, se debe mostrar todas las imágenes que se recolectaron durante las entrevistas, las emociones reconocidas para cada imagen y las coordenadas donde se encuentra los rostros. También, imprimir una lista con sublistas donde la primera sublista tiene la información de las personas que tienen únicamente hijos de género femenino, la segunda sublista tiene información de personas que tienen únicamente hijos de género masculino y la última sublista tiene información de personas que tienen hijos tanto de género femenino como másculino.

5. Obtener para cada persona entrevistada las emociones sin ordenar y guardar en una lista (una lista por entrevista) con sublistas la siguiente información: en la primera sublista colocar la identificación, el nombre, el género y la edad de la persona entrevistada, en las siguientes sublistas colocar las emociones expresadas por la persona. Por ejemplo, si la persona apareció en 10 fotogramas entonces se deben crear 10 sublistas, cada sublista pertenece a las emociones emitidas por el candidato en un fotograma.

6. Una vez creada esta listas (una por entrevista) con sublistas del punto anterior, se debe ordenar las sublistas de forma ascendente por la emoción felicidad (happiness) utilizando el técnica de ordenamiento Quicksort.

7. Para cada persona entrevistada muestre un gráfico para comparar las emociones reportadas durante la entrevista.

8. Incluya en el documento escrito la entrevista a dos personas. De aportar toda la información recolectada, las imágenes recolectadas en la entrevista con un cuadro en los rostros presentes. Además, debe mostrar la información de las emociones reportadas. También debe mostrar la información del entrevistador y el evaluador.

9. Hacer una nueva entrevista a una persona. Una persona existente (previamente almacena en los archivos) puede volver a ser entrevistada. Debe guardar la nueva entrevista en el mismo archivo agregando la información de esta nueva entrevista a la lista de entrevistas de dicha persona. Tome en cuenta que el entrevistador puede ser uno que no le ha realizado ninguna entrevista.

10. Agregar una evaluación para indicar si la persona será contratada. Una vez que una persona ha sido entrevistada un evaluador puede revisar toda la información y decir si la persona será contratada (Debe mostrar la información de la persona para que el evaluador la revise y debe aportar una propiedad para la persona que se indica llamada "estado" (el estado puede ser entrevistado, contratado y no contratado). Tome en cuenta que el evaluador puede cambiar el estado de la persona para indicar que está contratado o no contratado.

#Inquiry 1

Show all the information of all the interviews out of the objects, lists and dictionaries, besides the emotions, coordenates and images.
"""

def show_individual_info(x):
    """ This function shows all the information of instances inside a list.
    Arguments:
        Archive {list} -- List with people's instances.
    """

    # Code to show all the information in widgets.
    print()
    #To show the name.
    name = widgets.Button(description = str("Name: ") + x.name,
    layout=Layout(width = '30%', height = '30px'))
    display(name)

    #To show the ID.
    ID = widgets.Button(description = str("ID: ") + str(x.identification),
    layout=Layout(width = '30%', height = '30px'))
    display(ID)

    #To show the birth date.
    birth_date = widgets.Button(description = str("Birth date: ") + x.birth_date,
    layout=Layout(width = '30%', height = '30px'))
    display(birth_date)

    #To show the age.
    age= widgets.Button(description = str("Age: ") + str(x.age),
    layout=Layout(width = '30%', height = '30px'))
    display(age)

    #To show the nationality.
    nationality = widgets.Button(description = str("Nationality: ") + x.nationality,
    layout=Layout(width = '30%', height = '30px'))
    display(nationality)

    #To show the telephone number.
    telephone_number = widgets.Button(description = str("Telephone number: ") + str(x.telephone_numbers),
    layout=Layout(width = '30%', height = '30px'))
    display(telephone_number)

    #To show the email.
    email = widgets.Button(description = str("Email: ") + str(x.emails),
    layout=Layout(width = '30%', height = '30px'))
    display(email)

    #To show the gender.
    gender = widgets.Button(description = str("Gender: ") + x.gender,
    layout=Layout(width = '30%', height = '30px'))
    display(gender)

    #To show the address.
    address = widgets.Button(description = str("Address: ") + x.address,
    layout=Layout(width = '30%', height = '30px'))
    display(address)

    #To show the marital status.
    marital_status = widgets.Button(description = str("Marital Status: ") + x.marital_status,
    layout=Layout(width = '30%', height = '30px'))
    display(marital_status)

    #Code to show the children's information.
    for i, e in x.children.items():
      if i == "number":
        t = widgets.Button(description = str("children  ") + str(i) + str(": ") + str(e),
        layout=Layout(width = '30%', height = '30px'))
        display(t)
      else:
       for k in e:
         m = widgets.Button(description = str("info: ") + str(k[0]) + str(", ") + str(k[1]),
         layout=Layout(width = '30%', height = '30px'))
         display(m)

    #To show the job.
    job = widgets.Button(description = str("Job: ") + x.job,
    layout=Layout(width = '30%', height = '30px'))
    display(job)

    #To show the salary.
    salary = widgets.Button(description = str("Salary: ") + str(x.salary),
    layout=Layout(width = '30%', height = '30px'))
    display(salary)

    #To show the academic grade.
    academic_grade = widgets.Button(description = str("Academic grade: ") + x.academic_grade,
    layout=Layout(width = '30%', height = '30px'))
    display(academic_grade)

    #To show the happiness.
    happiness = widgets.Button(description = str("Highest happiness: ") + str(x.happiness),
    layout=Layout(width = '30%', height = '30px'))
    display(happiness)

    #To show the state.
    state = widgets.Button(description = str("State: ") + str(x.state),
    layout=Layout(width='30%', height='30px'))
    display(state)


    #Code to show images, emotions and coordenates
    for x in x.images:
        show_image(x[0])
        p = x[1][0][0]
        p = widgets.Button(description = "Coordenates: " + str(p[0 ]) + str(p[1]) + str(p[2]) + str(p[3]),
        layout=Layout(width ='30%', height ='30px'))
        display(p)
        for w, y  in x[2].items():
          t = ": "
          w = widgets.Button(description = str(w ) + str(t) + str(y),
          layout=Layout(width = '30%', height = '30px'))
          display(w)

from ipywidgets.widgets.widget_layout import Layout
def show_info(Archive):
  """ This function shows all the information of instances inside a list.
  Arguments:
        Archive {list} -- List with people's instances.
  """

  # Code to show all the information in widgets.
  for x in Archive:
    print()
    #To show the name.
    name = widgets.Button(description = str("Name: ") + x.name,
    layout=Layout(width = '30%', height = '30px'))
    display(name)

     #To show the ID.
    ID = widgets.Button(description = str("ID: ") + str(x.identification),
    layout=Layout(width = '30%', height = '30px'))
    display(ID)

    #To show the birth date.
    birth_date = widgets.Button(description = str("Birth date: ") + x.birth_date,
    layout=Layout(width = '30%', height = '30px'))
    display(birth_date)

    #To show the age.
    age= widgets.Button(description = str("Age: ") + str(x.age),
    layout=Layout(width = '30%', height = '30px'))
    display(age)

    #To show the nationality.
    nationality = widgets.Button(description = str("Nationality: ") + x.nationality,
    layout=Layout(width = '30%', height = '30px'))
    display(nationality)

    #To show the telephone_number.
    telephone_number = widgets.Button(description = str("Telephone number: ") + str(x.telephone_numbers),
    layout=Layout(width = '30%', height = '30px'))
    display(telephone_number)

    #To show the email.
    email = widgets.Button(description = str("Email: ") + str(x.emails),
    layout=Layout(width = '30%', height = '30px'))
    display(email)

    #To show the gender.
    gender = widgets.Button(description = str("Gender: ") + x.gender,
    layout=Layout(width = '30%', height = '30px'))
    display(gender)

    #To show the address.
    address = widgets.Button(description = str("Address: ") + x.address,
    layout=Layout(width = '30%', height = '30px'))
    display(address)

    #To show the marital status.
    marital_status = widgets.Button(description = str("Marital Status: ") + x.marital_status,
    layout=Layout(width = '30%', height = '30px'))
    display(marital_status)

    #To show the children's information
    for i, e in x.children.items():
      if i == "number":
        t = widgets.Button(description = str("Children  ") + str(i) + str(": ") + str(e),
        layout=Layout(width = '30%', height = '30px'))
        display(t)
      else:
       for k in e:
         m = widgets.Button(description = str("info: ") + str(k[0]) + str(", ") + str(k[1]),
         layout=Layout(width = '30%', height = '30px'))
         display(m)

    #To show the job.
    job = widgets.Button(description = str("Job: ") + x.job,
    layout=Layout(width = '30%', height = '30px'))
    display(job)

    #To show the salary.
    salary = widgets.Button(description = str("Salary: ") + str(x.salary),
    layout=Layout(width = '30%', height = '30px'))
    display(salary)

    #To show the academic grade.
    academic_grade = widgets.Button(description = str("Academic grade: ") + x.academic_grade,
    layout=Layout(width = '30%', height = '30px'))
    display(academic_grade)

    #To show the state.
    state = widgets.Button(description = str("State: ") + x.state,
    layout=Layout(width='30%', height='30px'))
    display(state)

    #Code to show the images, coordenates and emotions.
    for x in x.images:
        show_image(x[0])
        p = x[1][0][0]
        p = widgets.Button(description = "Coordenates: " + str(p[0 ]) + str(p[1]) + str(p[2]) + str(p[3]),
        layout=Layout(width ='30%', height ='30px'))
        display(p)
        for w, y  in x[2].items():
          t = ": "
          w = widgets.Button(description = str(w ) + str(t) + str(y),
          layout=Layout(width = '30%', height = '30px'))
          display(w)

show_info(Archive_interviewee)

"""#Inquiry 2

Show all the people information sorted out upwardly based on their aged and using the insertion method.
"""

#Library to know the current date.
from datetime import datetime
def knowagei(birthdate):
 """The function gets the age of a person based on their birth date.
    Arguments:
        birthdate {str} -- Birth date.
    Returns:
        age {int} -- Age.
 """
 now = datetime.now()
 actualyear = now.year
 actualmonth = now.month
 date_string = birthdate
 date = datetime.strptime(date_string, "%Y-%m-%d")
 day = date.day
 month = date.month
 year = date.year
 age = actualyear - year
 mont = month - actualmonth
 if mont > 0:
   age = age - 1
 return age

def insertion(Archive_interviewee):
  """The function gets a list and sorts it out by the insertion method.
    Arguments:
        Archive_interviewee {list} -- Unsorted list.
    Returns:
        newlis {list} -- Sorted list.
  """
  newlis = []
  li = list(Archive_interviewee)
  while len(li) != 0:
    m = 200
    for x in li:
      if knowagei(x.birth_date) < m:
        m = knowagei(x.birth_date)
        t = x
    print(t)
    newlis.append(t)
    li.remove(t)
  show_info(newlis)
insertion(Archive_interviewee)

"""#Inquiry 3

Show all the people information sorted out in descending based on the amount of children they have using the bubble method.
"""

def bubble(archive_interviewee):
    """This function takes a list and sorts it by the bubble method.
    Arguments:
         archive_interviewee {list} -- Unsorted list.
    Returns:
        list_ {list} -- Sorted list.
    """
    list_ = list(archive_interviewee)
    times = len(list_) - 1
    while times > 0:
        pos = 0
        while pos < times:
            if list_[pos].children["number"] < list_[pos + 1].children["number"]:
                temp = list_[pos]
                list_[pos] = list_[pos + 1]
                list_[pos + 1] = temp
            pos = pos + 1
        times = times -1
    show_info(list_)
bubble(Archive_interviewee)

"""#Inquiry 4

Show all people information sorted out in descending based on the amount of children using the quicksort method. Besides, print a list with sublists where the first sublist has the information of all people with only female children, the second sublist with the people with only male children and the third sublist with people with both.
"""

def divide(listn):
    """Arguments:
        listn {list} -- Unsorted list.
    Returns:
        [bigger,pivot,smaller] {list} -- List with sublists with the smaller values, the pivot and the bigger values.
    """
    smaller = []
    bigger = []
    pivot = listn[-1]
    for x in listn[:-1]:
      if x.children["number"] < pivot.children["number"]:
            smaller.append(x)
      else:
            bigger.append(x)
    return [bigger, pivot, smaller]

def quicksort(Archive):
    """The function sorts out a list using the quicksort method.
    Arguments:
        Archive {list} -- List of people's instances.
    Returns:
        list_ {list} -- List of people's instances sorted out based on the amount of children they have.
    """
    list_ = Archive.copy()
    if len(list_) > 0:
        list_ = divide(list_)
        cont = 0
        while cont < len(list_):
            e = list_[cont]
            if type(e) == list:
                if len(e) == 0:
                    del list_[cont]
                elif len(e) == 1:
                    list_[cont] = e[0]
                    cont = cont + 1
                else:
                    list_ = list_[:cont] + divide(e) + list_[cont + 1:]
            else:
                cont = cont + 1

    show_info(list_)
quicksort(Archive_interviewee)

def classify(Archive):
  """The function creates a list with sublists, one with the information of people with only female children,
  another one with both and the last one with only male children .
    Arguments:
        Archive {list} -- List with all dictionaries.
    Returns:
        checklist {list} -- Classified list.
  """
  male = []
  female = []
  both = []
  for x in Archive:
    if x.children['number'] != 0:
      for i in x.children['info']:
        if i[0] == 'female' and x not in female and x not in male:
            female.append(x)
        if i[0] == "male" and x not in male and x not in female:
          male.append(x)
        if i[0] == "male" and x in female:
          female.remove(x)
          both.append(x)
        if i[0] == "female" and x in male:
          male.remove(x)
          both.append(x)
  check_list = [female, male, both]
  print("[")
  #Code to print the lists
  for x in check_list:
    if x == []:
      print(x)
    if x != []:
     print("[")
     show_info(x)
     print("]")
  print("]")
classify(Archive_interviewee)

"""#Inquiry 5

Obtain for each person the emotions without sorting and save them in a list, with sublists with the ID, the name, the gender, and the age.
"""

def sublists(Archive):
 """The function creates a list with sublists with specified information.
    Arguments:
        Interviews {list} -- List with all dictionaries.
    Returns:
        generallist {list} -- Classified list.
 """
 generallist = []
 newl = []
 for x in Archive:
   person_lis = []
   person_lis.append(x.identification)
   person_lis.append(x.name)
   person_lis.append(x.gender)
   person_lis.append(x.age)
   emotion_list = []
   for i in x.images:
    for e in i:
     if type(e) == dict:
      emotion_list.append(e)

   newl.append(emotion_list)
   newl.insert(0, person_lis)
   generallist.append(newl)
   newl = []

 return generallist
p = sublists(Archive_interviewee)
generall = widgets.Button(description = str(p),
layout=Layout(width = '2000%', height = '100px'))
display(generall)

"""#Inquiry 6

Once this list is created, for each person sort the emotion list upwardly based on the emotion happiness.
"""

def divide_list(liss):
    """Arguments:
        liss {list} -- Unsorted list.
    Returns:
        [bigger,pivot,smaller] {list} -- List with sublists with the smaller values, the pivot and the bigger values.
    """
    smaller = []
    bigger = []
    pivot = liss[0]
    for x in liss[1:]:
        if x["happiness"] < pivot["happiness"]:
            smaller.append(x)
        else:
            bigger.append(x)
    return([smaller, pivot, bigger])

def quickSort(Interviews):
    """The function sorts out a list using the quicksort method.
    Arguments:
        Interviews {list} -- List of people's instances.
    Returns:
        Interviews {list} -- List of people's instances sorted out based on the emotion happiness.
    """
    if len(Interviews) > 0:
        Interviews = divide_list(Interviews)
        cont = 0
        while cont < len(Interviews):
            e = Interviews[cont]
            if type(e) == list:
                if len(e) == 0:
                    del Interviews[cont]
                elif len(e) == 1:
                    Interviews[cont] = e[0]
                    cont = cont + 1
                else:
                    Interviews = Interviews[:cont] + divide_list(e) + Interviews[cont+1:]
            else:
                cont = cont + 1

    return Interviews

def function(Archive):
  Archive_copy = list(Archive)
  for x in Archive_copy:
    x[1] = quickSort(x[1])
  return Archive_copy
t = sublists(Archive_interviewee)
o = function(t)
generalli = widgets.Button(description = str(o),
layout=Layout(width = '2000%', height = '100px'))
display(generalli)

"""#Inquiry 7

For each person show a graphic to compare the emotions.
"""

#Library to create a graphic.
import matplotlib.pyplot as plt
#This code access to the emotions dictionaries and creates a graphic for each one of them.
for x in Archive_interviewee:
   c = 0
   print(x.name)
   for i in x.images:
         emotion = i[2]
         names = list(emotion.keys())
         values = list(emotion.values())
         lif, st = plt.subplots()
         st.set_title('emotions')
         st.set_xlabel('emotions')
         st.set_ylabel('values')
         plt.bar(names, values)



         plt.show()

"""#Inquiry 8

Inlcude in the written document the interviews of two people with all information and the information of the interviewer and evaluator.

The information is included in the written document.

#Inquiry 9

Make an interview to a new person or a person that has already been interviewed.

Implemented in the system of the program.

Code to show the information of the archive_evaluator
"""

def show_info_evaluator(Archive):
  """ This function shows all the information of instances inside a list.
  Arguments:
        Archive {list} -- List with people's instances.
  """

  # Code to export all the information.
  for x in Archive:
    print()
    name = widgets.Button(description = str("Name: ") + x.name,
    layout=Layout(width = '30%', height = '30px'))
    display(name)

    ID = widgets.Button(description = str("ID: ") + str(x.identification),
    layout=Layout(width = '30%', height = '30px'))
    display(ID)

    birth_date = widgets.Button(description = str("Birth date: ") + str(x.birth_date),
    layout=Layout(width = '30%', height = '30px'))
    display(birth_date)

    age= widgets.Button(description = str("Age: ") + str(x.age),
    layout=Layout(width = '30%', height = '30px'))
    display(age)

    nationality = widgets.Button(description = str("Nationality: ") + x.nationality,
    layout=Layout(width = '30%', height = '30px'))
    display(nationality)

    telephone_number = widgets.Button(description = str("Telephone number: ") + str(x.telephone_numbers),
    layout=Layout(width = '30%', height = '30px'))
    display(telephone_number)

    email = widgets.Button(description = str("Email: ") + str(x.emails),
    layout=Layout(width = '30%', height = '30px'))
    display(email)

    gender = widgets.Button(description = str("Gender: ") + x.gender,
    layout=Layout(width = '30%', height = '30px'))
    display(gender)

    address = widgets.Button(description = str("Address: ") + x.address,
    layout=Layout(width = '30%', height = '30px'))
    display(address)

    specialty = widgets.Button(description = str("Specialty: ") + x.specialty,
    layout=Layout(width = '30%', height = '30px'))
    display(specialty)

    technical_programs = widgets.Button(description = str("Technical programs: ") + x.technical_programs,
    layout=Layout(width = '30%', height = '30px'))
    display(technical_programs)

    languages = widgets.Button(description = str("Lnaguages: ") + str(x.languages),
    layout=Layout(width = '30%', height = '30px'))
    display(languages)


show_info_evaluator(Archive_evaluator)

"""Show information of the interviewers"""

def show_info_interviewer(Archive):
  """ This function shows all the information of instances inside a list.
  Arguments:
        Archive {list} -- List with people's instances.
  """

  # Code to export all the information.
  for x in Archive:
    print()
    name = widgets.Button(description = str("Name: ") + x.name,
    layout=Layout(width = '30%', height = '30px'))
    display(name)

    ID = widgets.Button(description = str("ID: ") + str(x.identification),
    layout=Layout(width = '30%', height = '30px'))
    display(ID)

    birth_date = widgets.Button(description = str("Birth date: ") + str(x.birth_date),
    layout=Layout(width = '30%', height = '30px'))
    display(birth_date)

    age= widgets.Button(description = str("Age: ") + str(x.age),
    layout=Layout(width = '30%', height = '30px'))
    display(age)

    nationality = widgets.Button(description = str("Nationality: ") + x.nationality,
    layout=Layout(width = '30%', height = '30px'))
    display(nationality)

    telephone_number = widgets.Button(description = str("Telephone number: ") + str(x.telephone_numbers),
    layout=Layout(width = '30%', height = '30px'))
    display(telephone_number)

    email = widgets.Button(description = str("Email: ") + str(x.emails),
    layout=Layout(width = '30%', height = '30px'))
    display(email)

    gender = widgets.Button(description = str("Gender: ") + x.gender,
    layout=Layout(width = '30%', height = '30px'))
    display(gender)

    address = widgets.Button(description = str("Address: ") + x.address,
    layout=Layout(width = '30%', height = '30px'))
    display(address)

    code_number = widgets.Button(description = str("Code number: ") + str(x.code_number),
    layout=Layout(width = '30%', height = '30px'))
    display(code_number)

    certificate = widgets.Button(description = str("Certificate number: ") + str(x.certificate),
    layout=Layout(width = '30%', height = '30px'))
    display(certificate )

    experience = widgets.Button(description = str("Experience years: ") + str(x.experience),
    layout=Layout(width = '30%', height = '30px'))
    display(experience)

show_info_interviewer(Archive_interviewer)

"""#Inquiry 10

Add an evaluation to validate if the person will be hired or not, the person must have a property called state that dictates the state of the interview and the evaluator can change it.
"""

#Code to change the state of validation of an instance.
def replace(_):
 """This function replaces the attribute state of an instance"""
 def secondre(_):
    """This function looks for the person based on their ID and replaces the attribute state"""
    for x in Archive_interviewee:
      if x.identification == m.value:
          x.state = str(state.value)
    print("The state of the individual's interview has changed")
    with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistado", "wb") as entre:
      pickle.dump(Archive_interviewee, entre)

 #Code to look for the person
 for x in Archive_interviewee:
  if x.identification == m.value:
    P = x.state
    print(x.state)
    show_individual_info(x)
    print("Write the new stage of the interview")
    state = widgets.Dropdown(
    options=['Interviewed', 'Hired', 'Fired'],
    description='State: ',
    disabled=False,
    )
    button = widgets.Button(
    description = "Save information"
    )
    display(state)
    display(button)
    button.on_click(secondre)

#Code to ask for the ID
print("Interviews validation")
print("Write the ID of the interviewed person that is going to be evaluated: ")
m = widgets.BoundedIntText(
    value=7,
    min=0,
    max=1000000000,
    step=1,
    description='ID:',
    disabled=False
    )
boton = widgets.Button(
description = "Save information"
)

#Code to display the buttons
display(m)
display(boton)

#Comand to direct the operation to the function replace
boton.on_click(replace)

#Code to show the instances of the Archivo_Entrevistado
with open("/content/drive/MyDrive/Archive_III_project/Archivo_Entrevistado", "rb") as entre:
  Archive_interviewee = pickle.load(entre)
print("---------")
for x in Archive_interviewee:
  print(x)

"""#Images

https://drive.google.com/drive/folders/1-BJKfkAXJQliM00RNsbIgPW7pOMmJysR?usp=sharing

## Aspectos administrativos

* La tarea será desarrollada en equipos de trabajo de máximo 2 personas.
* Cualquier acción de plagio será sancionada con una nota de 0 y la carta al expediente respectiva para todos los
implicados.
* La fecha de entrega será la semana 17, el día de clases, antes de la hora de clases.
* Para llevar el control de versiones del proyecto se debe crear un repositorio en GitLab y agregar al profesor (agregarlo
a la cuenta amendez.tec@gmail.com).
* Para llevar el control del las tareas a realizar por participante en el proyecto debe utilizar la herramienta
https://trello.com/es y compartir el link en el mismo Google Doc en que se comparte el link de la plantilla de Overleaf. Pueden crear tab de todas las tareas o requerimientos, un tab para las tareas en proceso y un tab para las tareas hechas.
* La codificación y documentación interna deberá ser desarrollada en idioma inglés utilizando el estándar docString de Python.
*La documentación externa debe estar redactada en idioma inglés utilizando la herramienta Overleaf (utilizar la plantilla facilitada por el profesor). La documentación es evaluada en el curso de Introducción a la programación.
* Documentación del Código utilizando Docstring Conventions
* Introducción a Python la Guía de Estilo de Código en Python
* La entrega será mediante la plataforma TecDigital en el espacio de Proyecto – Etapa 2. Lo que debe subir es un archivo de tipo notebook cuya extensión es (.ipynb). Además, en este archivo deben venir los enlaces a las imagenes utilizados para la tarea.
* Se recomienda que se empiece a trabajar lo antes posible.

# "La programación es una habilidad que puedes cultivar en ti mismo y usar para cambiar el mundo". - Barack Obama
"""